module.exports = {
  apps: [
    {
      name: 'tarotfr-web',
      script: 'npm',
      args: 'start',
      cwd: '/var/www/tarotfr',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_SUPABASE_URL: 'https://amwwthdjnsnociqbodtz.supabase.co',
        NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtd3d0aGRqbnNub2NpcWJvZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NDAxNzAsImV4cCI6MjA3OTAxNjE3MH0.y7624P1g_GfqvXAGXJbmib1coM_UGPyNbMd7La4GD-U',
        NEXT_PUBLIC_WS_URL: 'wss://ws.tarotfr.com',
        SUPABASE_URL: 'https://amwwthdjnsnociqbodtz.supabase.co',
        SUPABASE_SERVICE_ROLE_KEY: 'YOUR_SERVICE_ROLE_KEY_HERE',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/var/www/tarotfr/logs/web-error.log',
      out_file: '/var/www/tarotfr/logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'tarotfr-ws',
      script: 'node',
      args: 'server-dist/server/websocket.js',
      cwd: '/var/www/tarotfr',
      env: {
        NODE_ENV: 'production',
        WS_PORT: 3001,
        SUPABASE_URL: 'https://amwwthdjnsnociqbodtz.supabase.co',
        SUPABASE_SERVICE_ROLE_KEY: 'YOUR_SERVICE_ROLE_KEY_HERE',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      error_file: '/var/www/tarotfr/logs/ws-error.log',
      out_file: '/var/www/tarotfr/logs/ws-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
